server:
  port: 1234
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Zensar@123
  jpa:
   hibernate:
    ddl-auto: update
  application:
     name: coupon-service
  config:
    import:
     - optional:configserver:http://localhost:8888/
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    service-url:
      defaulfZone: http://localhost:8761/eureka
      
  instance:
   prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    
   
#spring.config.import

      

    

  

    
 